### ISSUE TITLE
chat not available.

### ISSUE THREAD

**Issue by jcright73** [learn-co-curriculum/phase-0-intro-to-js-2-array-methods#15]
### Canvas Link

https://learning.flatironschool.com/courses/7201/assignments/256318?module_item_id=606304

### Concern

I have questions about the lab I am in, but I don't see a chat button anywhere. I know it is supposed to be in the lower right hand corner but it isn't.

**Comment by lizbur10** [comment]
Hi @jcright73 ! The chat is available 12pm to midnight, ET. If you're not seeing it during those hours, please reach out to operations@flatironschool.com.  Good luck!
