### ISSUE TITLE
Correct return value of cities.unshift('Boston', 'Chicago') to 4 from 3

### ISSUE THREAD

**Issue by joedietrich-dev** [learn-co-curriculum/phase-0-intro-to-js-2-array-methods#3]
Given an array of length 2, unshifting two additional elements will give a length of 4:

```
cities.unshift('Boston', 'Chicago');
// => 3
```

Should be

```
cities.unshift('Boston', 'Chicago');
// => 4
```

**Comment by ihollander** [comment]
Thanks for flagging! This issue was already fixed in this GitHub repo (https://github.com/learn-co-curriculum/phase-0-intro-to-js-2-array-methods/commit/e81236a8ac3f277fe9590ceb5b22343fe3474270).
