### ISSUE TITLE
Array Methods

### ISSUE THREAD

**Issue by jsltran3** [learn-co-curriculum/phase-0-intro-to-js-2-array-methods#4]
### Canvas Link

https://learning.flatironschool.com/courses/4789/pages/array-methods?module_item_id=292513

### Concern

Under Splice:

Notice that .splice() both mutated the original array (by removing a chunk) and returned a new array containing the removed chunk.

Shouldn't it read, "AND returned a new array containing the remaining chunk"? or the unremoved chunk? 

Because in the example:
```
const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

days.splice(2);
// => ["Wed", "Thu", "Fri", "Sat", "Sun"]

days;
// => ["Mon", "Tue"]
```

It looks like Mon/Tue remained and wasn't removed.

**Comment by lizbur10** [comment]
Hi @jsltran3! Thanks for posting this issue and sorry about the confusion!

The **_return value_** of the `splice` method is the array containing the removed elements, not the mutated original array. I have made an edit to the lesson to try to make that a little clearer. 

Note that the update will not be reflected in your canvas course, but it will be there for students moving forward.

Thanks for contributing to the Flatiron School curriculum 💙
